document.write('<b>Counting:</b><br><br>')
for(i=1;i<=15;i++){
    document.write(i+',')
}
document.write('<br><br>')
document.write('<b>Reverse Counting:</b><br><br>')
for(j=10;j>=1;j--){
    document.write(j+',')
}
document.write('<br><br>')
document.write('<b>Even:</b><br><br>')
for(k=0;k<=20;k=k+2){
    document.write(k+',')
}
document.write('<br><br>')
document.write('<b>Odd:</b><br><br>')
for(l=1;l<=19;l=l+2){
    document.write(l+',')
}
document.write('<br><br>')
document.write('<b>Series:</b><br><br>')
for(m=2;m<=20;m=m+2){
    document.write(m+'k'+',')
}
document.write('<br><br>')